/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Apps */
        get: operations["get_apps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["get_config"];
        /** Save */
        put: operations["save_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extensions */
        get: operations["get_extensions"];
        put?: never;
        /** Manage */
        post: operations["manage_extension"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/obs/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Obs */
        post: operations["test_obs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paired-devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Device */
        delete: operations["revoke_paired_device"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairing/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pairing */
        post: operations["rotate_pairing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/paths/pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pick */
        post: operations["pick_path"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/permissions/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permission */
        post: operations["open_permission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema */
        get: operations["get_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["get_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionArgument */
        ActionArgument: {
            /** Choices */
            choices?: components["schemas"]["Choice"][];
            /** Default */
            default?: string | number | boolean | null;
            /**
             * Description
             * @default
             */
            description?: string | {
                [key: string]: string;
            };
            /**
             * Label
             * @default
             */
            label?: string | {
                [key: string]: string;
            };
            /** Max */
            max?: number | null;
            /** Max Length */
            max_length?: number | null;
            /** Min */
            min?: number | null;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number" | "hotkey" | "page" | "script" | "password" | "boolean" | "select";
        } & {
            [key: string]: unknown;
        };
        /** ActionDocument */
        ActionDocument: {
            /** Type */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** ActionSpec */
        ActionSpec: {
            /** Arguments */
            arguments: components["schemas"]["ActionArgument"][];
            /** Capability */
            capability: string | null;
            /** Category */
            category: string;
            /** Color */
            color: string;
            description: components["schemas"]["Translations"];
            /**
             * Extension
             * @default
             */
            extension?: string;
            /**
             * Extension Name
             * @default
             */
            extension_name?: string | {
                [key: string]: string;
            };
            /** Icon */
            icon: string;
            /** Kind */
            kind: string;
            /** Supported */
            supported: boolean;
            title: components["schemas"]["Translations"];
        } & {
            [key: string]: unknown;
        };
        /** AgentState */
        AgentState: {
            /** Capabilities */
            capabilities: {
                [key: string]: boolean;
            };
            /** Clients */
            clients: components["schemas"]["ClientSummary"][];
            /** Config Revision */
            config_revision: number;
            /** Counters */
            counters: {
                [key: string]: number;
            };
            /** Discovery Port */
            discovery_port: number;
            /** Events */
            events: components["schemas"]["RuntimeEvent"][];
            /** Features */
            features: {
                [key: string]: boolean;
            };
            /** Hints */
            hints: string[];
            /** Listen */
            listen: string;
            /** Logs */
            logs: string[];
            notifications: components["schemas"]["NotificationStatus"];
            /** Paired Devices */
            paired_devices: components["schemas"]["PairedDevice"][];
            pairing: components["schemas"]["PairingState"];
            /** Pause Remaining */
            pause_remaining: number | null;
            /** Paused */
            paused: boolean;
            /** Platform */
            platform: string;
            /** Snapshot */
            snapshot: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Token Set */
            token_set: boolean;
            /** Version */
            version: string;
        } & {
            [key: string]: unknown;
        };
        /** Apps */
        Apps: {
            /** Apps */
            apps: string[];
        } & {
            [key: string]: unknown;
        };
        /** ButtonDocument */
        ButtonDocument: {
            /** Action */
            action: string | components["schemas"]["ActionDocument"];
            /** Color */
            color: string;
            /** Hold Action */
            hold_action?: string | components["schemas"]["ActionDocument"] | null;
            /**
             * Hold Label
             * @default
             */
            hold_label?: string | {
                [key: string]: string;
            };
            /** Icon */
            icon: string;
            /** Id */
            id: string;
            /** Label */
            label: string | {
                [key: string]: string;
            };
            /** Slot */
            slot: number;
            /**
             * Toggle
             * @default
             */
            toggle?: string;
        } & {
            [key: string]: unknown;
        };
        /** ButtonInput */
        ButtonInput: {
            /** Action */
            action?: string | components["schemas"]["ActionDocument"];
            /** Color */
            color?: string;
            /** Hold Action */
            hold_action?: string | components["schemas"]["ActionDocument"];
            /** Hold Label */
            hold_label?: string | {
                [key: string]: string;
            };
            /** Icon */
            icon?: string;
            /** Id */
            id: string;
            /** Label */
            label?: string | {
                [key: string]: string;
            };
            /** Slot */
            slot?: number;
            /** Toggle */
            toggle?: string;
        };
        /** Catalog */
        Catalog: {
            /** Actions */
            actions: components["schemas"]["ActionSpec"][];
            /** Capabilities */
            capabilities: {
                [key: string]: boolean;
            };
            /** Dashboards */
            dashboards: components["schemas"]["Dashboard"][];
            /** Defaults */
            defaults: {
                [key: string]: string | number;
            };
            /** Extension Sources */
            extension_sources: components["schemas"]["Dashboard"][];
            /** Features */
            features: components["schemas"]["FeatureSpec"][];
            /** Icons */
            icons: string[];
            keys: components["schemas"]["Keys"];
            /** Layouts */
            layouts: string[];
            limits: components["schemas"]["Limits"];
            /** Locales */
            locales: string[];
            /** Sources */
            sources: string[];
        } & {
            [key: string]: unknown;
        };
        /** Choice */
        Choice: {
            /** Label */
            label: string | {
                [key: string]: string;
            };
            /** Value */
            value: string;
        } & {
            [key: string]: unknown;
        };
        /** ClientSummary */
        ClientSummary: {
            /** Address */
            address: string;
            /**
             * Device Id
             * @default
             */
            device_id?: string;
            /** Id */
            id: number;
            /**
             * Name
             * @default
             */
            name?: string;
        } & {
            [key: string]: unknown;
        };
        /** ConfigDocument */
        ConfigDocument: {
            /** Features */
            features: {
                [key: string]: boolean;
            };
            integrations: components["schemas"]["Integrations"];
            /** Pages */
            pages: components["schemas"]["PageDocument"][];
            /** Revision */
            revision: number;
            /** Scripts */
            scripts?: {
                [key: string]: string[];
            };
            server: components["schemas"]["ServerSettings"];
        } & {
            [key: string]: unknown;
        };
        /** ConfigInput */
        ConfigInput: {
            /** Features */
            features?: {
                [key: string]: boolean;
            };
            integrations?: components["schemas"]["IntegrationsInput"];
            /** Pages */
            pages: components["schemas"]["PageInput"][];
            /** Revision */
            revision?: number;
            /** Scripts */
            readonly scripts?: {
                [key: string]: string[];
            };
            server?: components["schemas"]["ServerInput"];
        };
        /** ConfigRead */
        ConfigRead: {
            config: components["schemas"]["ConfigDocument"];
            /** Path */
            path: string;
        } & {
            [key: string]: unknown;
        };
        /** ConfigSaved */
        ConfigSaved: {
            config: components["schemas"]["ConfigDocument"];
            /** Saved */
            saved: boolean;
        } & {
            [key: string]: unknown;
        };
        /** Configure */
        Configure: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "configure";
            /** Settings */
            settings: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** Contribution */
        Contribution: {
            /** Description */
            description: string | {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /** Title */
            title: string | {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** Dashboard */
        Dashboard: {
            /**
             * Description
             * @default
             */
            description?: string | {
                [key: string]: string;
            };
            /**
             * Icon
             * @default
             */
            icon?: string;
            /** Name */
            name: string;
            /** Supported */
            supported: boolean;
            /**
             * Title
             * @default
             */
            title?: string | {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** DeviceRevoked */
        DeviceRevoked: {
            /** Revoked */
            revoked: boolean;
        } & {
            [key: string]: unknown;
        };
        /** Enable */
        Enable: {
            /** Digest */
            digest: string;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "enable";
            /** Trust */
            trust: boolean;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Error */
            error: string;
            /** Request Id */
            request_id: string;
        };
        /** ExtensionCatalog */
        ExtensionCatalog: {
            /** Api Version */
            api_version: number;
            /** Directory */
            directory: string;
            /** Errors */
            errors: string[];
            /** Extensions */
            extensions: components["schemas"]["InstalledExtension"][];
        } & {
            [key: string]: unknown;
        };
        /** ExtensionManifest */
        ExtensionManifest: {
            /** Actions */
            actions: components["schemas"]["Contribution"][];
            /** Api Version */
            api_version: number;
            /** Author */
            author: string;
            /** Dashboards */
            dashboards: components["schemas"]["Contribution"][];
            /** Description */
            description: string | {
                [key: string]: string;
            };
            /** Id */
            id: string;
            /** Name */
            name: string | {
                [key: string]: string;
            };
            /** Permissions */
            permissions: string[];
            /** Platforms */
            platforms: string[];
            /** Settings */
            settings: components["schemas"]["ActionArgument"][];
            /** Sources */
            sources: components["schemas"]["Contribution"][];
            /** Version */
            version: string;
        } & {
            [key: string]: unknown;
        };
        /** FeatureSpec */
        FeatureSpec: {
            /** Available */
            available: boolean;
            description: components["schemas"]["Translations"];
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            /** Parent */
            parent: string | null;
            /** Platforms */
            platforms: string[];
            title: components["schemas"]["Translations"];
        } & {
            [key: string]: unknown;
        };
        /** Health */
        Health: {
            /** Components */
            components: {
                [key: string]: string;
            };
            /** Last Collection Age */
            last_collection_age: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded" | "stopping";
            /** Uptime */
            uptime: number;
        } & {
            [key: string]: unknown;
        };
        /** Install */
        Install: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "install" | "rescan";
        };
        /** InstalledExtension */
        InstalledExtension: {
            /** Digest */
            digest: string;
            /** Enabled */
            enabled: boolean;
            /** Error */
            error: string;
            manifest: components["schemas"]["ExtensionManifest"];
            /** Secret Fields Set */
            secret_fields_set: string[];
            /** Settings */
            settings: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Status */
            status: string;
            /** Updated At */
            updated_at: number;
        } & {
            [key: string]: unknown;
        };
        /** Integrations */
        Integrations: {
            obs: components["schemas"]["ObsSettings"];
        } & {
            [key: string]: unknown;
        };
        /** IntegrationsInput */
        IntegrationsInput: {
            obs?: components["schemas"]["ObsInput"];
        };
        /**
         * JsonBody
         * @description Keep JSON recursive references scoped to a Pydantic model.
         */
        JsonBody: components["schemas"]["JsonValue"];
        JsonValue: unknown;
        /** Key */
        Key: {
            /** Group */
            group: string;
            /** Label En */
            label_en: string;
            /** Label Fr */
            label_fr: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /** KeyDescription */
        KeyDescription: {
            /** Label En */
            label_en: string;
            /** Label Fr */
            label_fr: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /** Keys */
        Keys: {
            /** Groups */
            groups: string[];
            /** Keys */
            keys: components["schemas"]["Key"][];
            /** Modifiers */
            modifiers: components["schemas"]["KeyDescription"][];
        } & {
            [key: string]: unknown;
        };
        /** Limits */
        Limits: {
            /** Buttons Per Page */
            buttons_per_page: number;
            /** Id */
            id: number;
            /** Label */
            label: number;
            /** Pages */
            pages: number;
        } & {
            [key: string]: number | number[];
        };
        /** NotificationStatus */
        NotificationStatus: {
            /**
             * Access
             * @default unknown
             */
            access?: string;
            /**
             * Available
             * @default false
             */
            available?: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled?: boolean;
            /**
             * Error
             * @default
             */
            error?: string;
            /**
             * Settings Action
             * @default
             */
            settings_action?: string;
        } & {
            [key: string]: unknown;
        };
        /** ObsInput */
        ObsInput: {
            /** Enabled */
            enabled?: boolean;
            /** Host */
            host?: string;
            /** Password */
            password?: string;
            /** Port */
            port?: number;
            /** Timeout */
            timeout?: number;
        };
        /** ObsSettings */
        ObsSettings: {
            /** Enabled */
            enabled: boolean;
            /** Host */
            host: string;
            /** Password */
            password: string;
            /** Port */
            port: number;
            /** Timeout */
            timeout: number;
        } & {
            [key: string]: unknown;
        };
        /** ObsStatus */
        ObsStatus: {
            /** Connected */
            connected: boolean;
            /**
             * Current Scene
             * @default
             */
            current_scene?: string;
            /**
             * Obs Version
             * @default
             */
            obs_version?: string;
            /** Scenes */
            scenes?: string[];
        } & {
            [key: string]: unknown;
        };
        /** OperationResult */
        OperationResult: {
            /**
             * Cancelled
             * @default false
             */
            cancelled?: boolean;
            /**
             * Ok
             * @default false
             */
            ok?: boolean;
        } & {
            [key: string]: unknown;
        };
        /** PageDocument */
        PageDocument: {
            /** Buttons */
            buttons: components["schemas"]["ButtonDocument"][];
            /** Dashboard */
            dashboard: string;
            /** Icon */
            icon: string;
            /** Id */
            id: string;
            /**
             * Layout
             * @default grid
             * @enum {string}
             */
            layout?: "grid" | "list";
            /**
             * Source
             * @default
             */
            source?: string;
            /** Title */
            title: string | {
                [key: string]: string;
            };
        } & {
            [key: string]: unknown;
        };
        /** PageInput */
        PageInput: {
            /** Buttons */
            buttons?: components["schemas"]["ButtonInput"][];
            /** Dashboard */
            dashboard?: string;
            /** Icon */
            icon?: string;
            /** Id */
            id: string;
            /**
             * Layout
             * @enum {string}
             */
            layout?: "grid" | "list";
            /** Source */
            source?: string;
            /** Title */
            title?: string | {
                [key: string]: string;
            };
        };
        /** PairedDevice */
        PairedDevice: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Last Seen */
            last_seen: string;
            /** Name */
            name: string;
        } & {
            [key: string]: unknown;
        };
        /** PairingState */
        PairingState: {
            /** Code */
            code: string;
            /** Expires In */
            expires_in: number;
            /** Required */
            required: boolean;
        } & {
            [key: string]: unknown;
        };
        /** PathRequest */
        PathRequest: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "file" | "folder";
        };
        /** PathSelection */
        PathSelection: {
            /** Cancelled */
            cancelled: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "file" | "folder";
            /** Path */
            path: string;
        } & {
            [key: string]: unknown;
        };
        /** PermissionOpened */
        PermissionOpened: {
            /** Opened */
            opened: boolean;
            /** Permission */
            permission: string;
        } & {
            [key: string]: unknown;
        };
        /** PermissionRequest */
        PermissionRequest: {
            /** Permission */
            permission: string;
        };
        /** Remove */
        Remove: {
            /** Confirm */
            confirm: boolean;
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "remove";
        };
        /** RuntimeEvent */
        RuntimeEvent: {
            /** Fields */
            fields: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Level
             * @enum {string}
             */
            level: "debug" | "info" | "warning" | "error";
            /** Message */
            message: string;
            /** Name */
            name: string;
            /** Timestamp */
            timestamp: string;
        } & {
            [key: string]: unknown;
        };
        /** ServerInput */
        ServerInput: {
            /** Host */
            host?: string;
            /** Poll Interval */
            poll_interval?: number;
            /** Port */
            port?: number;
            /** Token */
            token?: string;
            /** Volume Step */
            volume_step?: number;
        };
        /** ServerSettings */
        ServerSettings: {
            /** Host */
            host: string;
            /** Poll Interval */
            poll_interval: number;
            /** Port */
            port: number;
            /** Token */
            token: string;
            /** Volume Step */
            volume_step: number;
        } & {
            [key: string]: unknown;
        };
        /** TargetOperation */
        TargetOperation: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            operation: "disable" | "restart";
        };
        /** Translations */
        Translations: {
            /** En */
            en: string;
            /** Fr */
            fr: string;
        } & {
            [key: string]: unknown;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Error */
            error: string;
            /** Valid */
            valid: boolean;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_apps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Apps"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRead"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    save_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSaved"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validate_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_extensions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionCatalog"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    manage_extension: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Install"] | components["schemas"]["TargetOperation"] | components["schemas"]["Enable"] | components["schemas"]["Configure"] | components["schemas"]["Remove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationResult"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    test_obs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObsInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObsStatus"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    revoke_paired_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceRevoked"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rotate_pairing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingState"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    pick_path: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathSelection"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    open_permission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionOpened"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_state: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentState"];
                };
            };
            /** @description Malformed body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Local session refused */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict or unavailable integration */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Agent unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
