#!/usr/bin/env python3
"""Generate both community QR assets. Requires: pip install qrcode==8.2."""
import json
from pathlib import Path
import qrcode

root = Path(__file__).resolve().parents[1]
url = json.loads((root / "resources/community.json").read_text())["invite_url"]
qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, border=4)
qr.add_data(url)
qr.make(fit=True)
matrix = qr.get_matrix()
size = len(matrix)
rects = ''.join(f'<rect x="{x}" y="{y}" width="1" height="1"/>'
                for y, row in enumerate(matrix) for x, dark in enumerate(row) if dark)
svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" shape-rendering="crispEdges"><rect width="{size}" height="{size}" fill="white"/><g fill="black">{rects}</g></svg>\n'
(root / "apps/desktop/frontend/public/community-qr.svg").write_text(svg)
(root / "apps/desktop/frontend/src/utils/community.ts").write_text(
    '// Generated by tools/build_community_qr.py; edit resources/community.json.\n'
    f'export const COMMUNITY_URL = {json.dumps(url)};\n')
rows = ',\n'.join('    {' + ','.join('1' if cell else '0' for cell in row) + '}' for row in matrix)
(root / "apps/console/source/ui/community_qr.h").write_text(
    '// Generated by tools/build_community_qr.py; includes the four-module quiet zone.\n'
    '#pragma once\n' + f'#define COMMUNITY_URL {json.dumps(url)}\n'
    + f'#define COMMUNITY_QR_SIZE {size}\n'
    + f'static const unsigned char community_qr[COMMUNITY_QR_SIZE][COMMUNITY_QR_SIZE] = {{\n{rows}\n}};\n')
print(f'Generated {size} × {size} QR for {url}')
