/** Export the PC sprite atlas from the production 3DS artwork.
 * cc -std=c11 -Iapps/console/source/graphics tools/export_decky_sprite.c \
 *    apps/console/source/graphics/decky.c -lm -o /tmp/export-decky
 * /tmp/export-decky apps/desktop/frontend/public/decky.svg
 */
#include "decky.h"
#include <stdio.h>
#include <stdlib.h>

static void paint(void *context, int x, int y, int w, int h, uint32_t rgb)
{
    fprintf(context, "<rect x='%d' y='%d' width='%d' height='%d' fill='#%06x'/>",
            x, y, w, h, (unsigned)rgb);
}
int main(int argc, char **argv)
{
    if (argc != 2) return EXIT_FAILURE;
    FILE *out = fopen(argv[1], "w");
    if (!out) return EXIT_FAILURE;
    fputs("<!-- Generated by tools/export_decky_sprite.c; edit graphics/decky.c instead. -->\n"
          "<svg xmlns='http://www.w3.org/2000/svg' width='320' height='240' viewBox='0 0 320 240' shape-rendering='crispEdges'>",out);
    for (int mood = 0; mood < DECKY_MOOD_COUNT; mood++) {
        for (int frame = 0; frame < 8; frame++) {
            fprintf(out,"<g transform='translate(%d %d)'>",frame*40,mood*40);
            const float time = frame == 7 ? 4.5f : frame*.5f;
            decky_draw((DeckyMood)mood, time, paint, out);
            fputs("</g>",out);
        }
    }
    fputs("</svg>\n",out);
    const int failed = ferror(out);
    return fclose(out) == 0 && !failed ? EXIT_SUCCESS : EXIT_FAILURE;
}
