/** Generate logo/README banners from the native Decky artwork.
 * Build like export_decky_sprite.c, then run: export-decky-brand output.svg logo|en|fr
 */
#include "decky.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static void paint(void *out, int x, int y, int w, int h, uint32_t rgb)
{
    fprintf(out,"<rect x='%d' y='%d' width='%d' height='%d' fill='#%06x'/>",x,y,w,h,(unsigned)rgb);
}
int main(int argc, char **argv)
{
    if (argc != 3) return EXIT_FAILURE;
    const int logo = strcmp(argv[2],"logo") == 0;
    const int fr = strcmp(argv[2],"fr") == 0;
    if (!logo && !fr && strcmp(argv[2],"en")) return EXIT_FAILURE;
    FILE *out = fopen(argv[1],"w");
    if (!out) return EXIT_FAILURE;
    fputs("<!-- Generated by tools/export_decky_brand.c from the native Decky renderer. -->\n",out);
    if (logo) {
        fputs("<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40' shape-rendering='crispEdges'>",out);
        decky_draw(DECKY_WAVE,0,paint,out);
    } else {
        fputs("<svg xmlns='http://www.w3.org/2000/svg' width='1200' height='440' viewBox='0 0 1200 440'>"
              "<defs><radialGradient id='glow'><stop stop-color='#66cb10' stop-opacity='.16'/><stop offset='1' stop-color='#66cb10' stop-opacity='0'/></radialGradient></defs>"
              "<rect width='1200' height='440' rx='28' fill='#111514'/>"
              "<ellipse cx='270' cy='210' rx='320' ry='220' fill='url(#glow)'/>"
              "<rect x='24' y='24' width='1152' height='392' rx='18' fill='none' stroke='#ffffff' stroke-opacity='.07'/>"
              "<g transform='translate(106 80) scale(7)' shape-rendering='crispEdges'>",out);
        decky_draw(DECKY_WAVE,0,paint,out);
        fputs("</g><g font-family='Inter,system-ui,-apple-system,Segoe UI,sans-serif'>",out);
        fputs("<text x='454' y='234' fill='#f2f6ee' font-size='98' font-weight='800' letter-spacing='-5'>3Decks</text>",out);
        fprintf(out,"<text x='460' y='287' fill='#bdc8c0' font-size='24'>%s</text>",
                fr ? "Votre 3DS. Votre PC. Un peu de compagnie." : "Your 3DS. Your desktop. A little company.");
        fputs("</g>",out);
    }
    fputs("</svg>\n",out);
    const int failed = ferror(out);
    return fclose(out) == 0 && !failed ? EXIT_SUCCESS : EXIT_FAILURE;
}
