"""Explicit console adapter contract, independent of its runtime implementation."""

from __future__ import annotations
import asyncio
from collections import Counter, deque
from pathlib import Path
from typing import Any, Protocol
from ..actions import ActionOutcome, Dispatcher
from ..config import Action, ButtonConfig, Config
from ..extensions.manager import ExtensionManager
from ..pairing import PairingManager
from ..platforms.base import Platform, SystemSnapshot
from ..services.bundle import Services
from ..services.executor import WorkPool
from .parts import ArtworkCache, Client


class AgentPort(Protocol):
    config: Config
    platform: Platform
    dispatcher: Dispatcher
    extensions: ExtensionManager
    pairing: PairingManager
    clients: set[Client]
    _client_tasks: set[asyncio.Task[None]]
    services: Services
    native_pool: WorkPool
    actions_pool: WorkPool
    extension_actions_pool: WorkPool
    config_path: Path | None
    verbose: bool
    _logs: deque[str]
    _events: deque[dict[str, Any]]
    _counters: Counter[str]
    _last_payload: dict[str, Any] | None
    _refresh_event: asyncio.Event | None
    _slow_confirm: bool
    _published_windows: list[tuple[str, str]]
    _artwork: ArtworkCache
    _discovery_name: str
    _discovery_transport: asyncio.DatagramTransport | None
    last_collection_at: float | None

    @property
    def controls_paused(self) -> bool: ...

    def log(self, message: str) -> None: ...
    def debug(self, message: str) -> None: ...
    def event(
        self, name: str, message: str = "", level: str = "info", **fields: object
    ) -> None: ...
    def _wake(self) -> asyncio.Event: ...
    def _audience(self) -> list[Client]: ...
    def _has_dynamic_pages(self) -> bool: ...
    def _fill_dynamic_pages(
        self, windows: list[tuple[str, str]], active_app: str = ""
    ) -> None: ...
    def _config_message(self, locale: str = "en") -> dict[str, Any]: ...
    def _delta_since_last(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def _schedule_confirmation(self, outcome: ActionOutcome) -> None: ...
    def discovery_payload(self) -> dict[str, Any]: ...
    async def _broadcast_config(self) -> None: ...
    async def _drop(self, client: Client) -> None: ...
    async def _refresh_state(self) -> None: ...
    async def _republish_windows(self, active_app: str) -> None: ...
    async def _refresh_artwork(
        self, snapshot: SystemSnapshot, payload: dict[str, Any]
    ) -> bytes | None: ...
    async def _publish(self, delta: dict[str, Any], art: bytes | None) -> None: ...
    async def _collect_safely(self) -> None: ...
    async def _confirm_after_action(self) -> None: ...
    async def _wait_for_wake(self) -> bool: ...
    async def reload_config_if_changed(self) -> bool: ...
    async def _read_messages(
        self, client: Client, reader: asyncio.StreamReader
    ) -> None: ...
    async def _dispatch_available(self, client: Client) -> bool: ...
    async def _handle_message(
        self, client: Client, message: dict[str, Any]
    ) -> None: ...
    async def _handle_hello(self, client: Client, message: dict[str, Any]) -> None: ...
    async def _handle_button(self, client: Client, message: dict[str, Any]) -> None: ...
    async def _handle_value(self, client: Client, message: dict[str, Any]) -> None: ...
    async def _handle_config_request(
        self, client: Client, message: dict[str, Any]
    ) -> None: ...
    async def _handle_ping(self, client: Client, message: dict[str, Any]) -> None: ...
    async def _accept_handshake(
        self, client: Client, message: dict[str, Any]
    ) -> bool: ...
    async def _reject_handshake(
        self, client: Client, reason: str, note: str, code: str = ""
    ) -> None: ...
    async def _send_initial_state(self, client: Client) -> None: ...
    async def _resolve_target(
        self, client: Client, request_id: int, page_id: str, button_id: str
    ) -> tuple[ButtonConfig | None, Action | None] | None: ...
    async def _run_action(
        self,
        button: ButtonConfig | None,
        action: Action | None,
        hold: bool,
        language: str,
    ) -> tuple[ActionOutcome, float]: ...
